name: pypeit
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pyyaml>=5.1
  - requests>=2.23
  - packaging>=19.0
  - numpy>=1.18
  - scipy>=1.4
  - scikit-learn>=0.20
  - astropy>=4.0
  - pyside2>=5.12
  - setuptools>=46.4
  - numba>=0.39
  - matplotlib>=3.1
  - configobj>=5.0.6
  - ipython>=7.2
  - extension-helpers>=0.1
  - ginga>=3.0
  - linetools>=0.3
  - PySide2>=5.0
  - pytest>=3.0.7
